export const countryCodes  = [
    { label: 'Afghanistan (+93)', value: 'Afghanistan (+93)' },
    { label: 'Albania (+355)', value: 'Albania (+355)' },
    { label: 'Algeria (+213)', value: 'Algeria (+213)' },
    { label: 'Andorra (+376)', value: 'Andorra (+376)' },
    { label: 'Angola (+244)', value: 'Angola (+244)' },
    { label: 'Argentina (+54)', value: 'Argentina (+54)' },
    { label: 'Armenia (+374)', value: 'Armenia (+374)' },
    { label: 'Australia (+61)', value: 'Australia (+61)' },
    { label: 'Austria (+43)', value: 'Austria (+43)' },
    { label: 'Azerbaijan (+994)', value: 'Azerbaijan (+994)' },
    { label: 'Bahamas (+1-242)', value: 'Bahamas (+1-242)' },
    { label: 'Bahrain (+973)', value: 'Bahrain (+973)' },
    { label: 'Bangladesh (+880)', value: 'Bangladesh (+880)' },
    { label: 'Barbados (+1-246)', value: 'Barbados (+1-246)' },
    { label: 'Belarus (+375)', value: 'Belarus (+375)' },
    { label: 'Belgium (+32)', value: 'Belgium (+32)' },
    { label: 'Belize (+501)', value: 'Belize (+501)' },
    { label: 'Benin (+229)', value: 'Benin (+229)' },
    { label: 'Bhutan (+975)', value: 'Bhutan (+975)' },
    { label: 'Bolivia (+591)', value: 'Bolivia (+591)' },
    { label: 'Bosnia and Herzegovina (+387)', value: 'Bosnia and Herzegovina (+387)' },
    { label: 'Botswana (+267)', value: 'Botswana (+267)' },
    { label: 'Brazil (+55)', value: 'Brazil (+55)' },
    { label: 'Brunei (+673)', value: 'Brunei (+673)' },
    { label: 'Bulgaria (+359)', value: 'Bulgaria (+359)' },
    { label: 'Burkina Faso (+226)', value: 'Burkina Faso (+226)' },
    { label: 'Burundi (+257)', value: 'Burundi (+257)' },
    { label: 'Cambodia (+855)', value: 'Cambodia (+855)' },
    { label: 'Cameroon (+237)', value: 'Cameroon (+237)' },
    { label: 'Canada (+1)', value: 'Canada (+1)' },
    { label: 'Chad (+235)', value: 'Chad (+235)' },
    { label: 'Chile (+56)', value: 'Chile (+56)' },
    { label: 'China (+86)', value: 'China (+86)' },
    { label: 'Colombia (+57)', value: 'Colombia (+57)' },
    { label: 'Congo (+242)', value: 'Congo (+242)' },
    { label: 'Costa Rica (+506)', value: 'Costa Rica (+506)' },
    { label: 'Croatia (+385)', value: 'Croatia (+385)' },
    { label: 'Cuba (+53)', value: 'Cuba (+53)' },
    { label: 'Cyprus (+357)', value: 'Cyprus (+357)' },
    { label: 'Czech Republic (+420)', value: 'Czech Republic (+420)' },
    { label: 'Denmark (+45)', value: 'Denmark (+45)' },
    { label: 'Dominican Republic (+1-809)', value: 'Dominican Republic (+1-809)' },
    { label: 'Ecuador (+593)', value: 'Ecuador (+593)' },
    { label: 'Egypt (+20)', value: 'Egypt (+20)' },
    { label: 'El Salvador (+503)', value: 'El Salvador (+503)' },
    { label: 'Estonia (+372)', value: 'Estonia (+372)' },
    { label: 'Ethiopia (+251)', value: 'Ethiopia (+251)' },
    { label: 'Fiji (+679)', value: 'Fiji (+679)' },
    { label: 'Finland (+358)', value: 'Finland (+358)' },
    { label: 'France (+33)', value: 'France (+33)' },
    { label: 'Gabon (+241)', value: 'Gabon (+241)' },
    { label: 'Gambia (+220)', value: 'Gambia (+220)' },
    { label: 'Georgia (+995)', value: 'Georgia (+995)' },
    { label: 'Germany (+49)', value: 'Germany (+49)' },
    { label: 'Ghana (+233)', value: 'Ghana (+233)' },
    { label: 'Greece (+30)', value: 'Greece (+30)' },
    { label: 'Grenada (+1-473)', value: 'Grenada (+1-473)' },
    { label: 'Guatemala (+502)', value: 'Guatemala (+502)' },
    { label: 'Guinea (+224)', value: 'Guinea (+224)' },
    { label: 'Guyana (+592)', value: 'Guyana (+592)' },
    { label: 'Haiti (+509)', value: 'Haiti (+509)' },
    { label: 'Honduras (+504)', value: 'Honduras (+504)' },
    { label: 'Hungary (+36)', value: 'Hungary (+36)' },
    { label: 'Iceland (+354)', value: 'Iceland (+354)' },
    { label: 'India (+91)', value: 'India (+91)' },
    { label: 'Indonesia (+62)', value: 'Indonesia (+62)' },
    { label: 'Iran (+98)', value: 'Iran (+98)' },
    { label: 'Iraq (+964)', value: 'Iraq (+964)' },
    { label: 'Ireland (+353)', value: 'Ireland (+353)' },
    { label: 'Israel (+972)', value: 'Israel (+972)' },
    { label: 'Italy (+39)', value: 'Italy (+39)' },
    { label: 'Jamaica (+1-876)', value: 'Jamaica (+1-876)' },
    { label: 'Japan (+81)', value: 'Japan (+81)' },
    { label: 'Jordan (+962)', value: 'Jordan (+962)' },
    { label: 'Kazakhstan (+7)', value: 'Kazakhstan (+7)' },
    { label: 'Kenya (+254)', value: 'Kenya (+254)' },
    { label: 'Kuwait (+965)', value: 'Kuwait (+965)' },
    { label: 'Kyrgyzstan (+996)', value: 'Kyrgyzstan (+996)' },
    { label: 'Laos (+856)', value: 'Laos (+856)' },
    { label: 'Latvia (+371)', value: 'Latvia (+371)' },
    { label: 'Lebanon (+961)', value: 'Lebanon (+961)' },
    { label: 'Lesotho (+266)', value: 'Lesotho (+266)' },
    { label: 'Liberia (+231)', value: 'Liberia (+231)' },
    { label: 'Libya (+218)', value: 'Libya (+218)' },
    { label: 'Lithuania (+370)', value: 'Lithuania (+370)' },
    { label: 'Luxembourg (+352)', value: 'Luxembourg (+352)' },
    { label: 'Madagascar (+261)', value: 'Madagascar (+261)' },
    { label: 'Malawi (+265)', value: 'Malawi (+265)' },
    { label: 'Malaysia (+60)', value: 'Malaysia (+60)' },
    { label: 'Maldives (+960)', value: 'Maldives (+960)' },
    { label: 'Mali (+223)', value: 'Mali (+223)' },
    { label: 'Malta (+356)', value: 'Malta (+356)' },
    { label: 'Mexico (+52)', value: 'Mexico (+52)' },
    { label: 'Moldova (+373)', value: 'Moldova (+373)' },
    { label: 'Monaco (+377)', value: 'Monaco (+377)' },
    { label: 'Mongolia (+976)', value: 'Mongolia (+976)' },
    { label: 'Montenegro (+382)', value: 'Montenegro (+382)' },
    { label: 'Morocco (+212)', value: 'Morocco (+212)' },
    { label: 'Mozambique (+258)', value: 'Mozambique (+258)' },
    { label: 'Myanmar (+95)', value: 'Myanmar (+95)' },
    { label: 'Namibia (+264)', value: 'Namibia (+264)' },
    { label: 'Nepal (+977)', value: 'Nepal (+977)' },
    { label: 'Netherlands (+31)', value: 'Netherlands (+31)' },
    { label: 'New Zealand (+64)', value: 'New Zealand (+64)' },
    { label: 'Nicaragua (+505)', value: 'Nicaragua (+505)' },
    { label: 'Niger (+227)', value: 'Niger (+227)' },
    { label: 'Nigeria (+234)', value: 'Nigeria (+234)' },
    { label: 'North Korea (+850)', value: 'North Korea (+850)' },
    { label: 'Norway (+47)', value: 'Norway (+47)' },
    { label: 'Oman (+968)', value: 'Oman (+968)' },
    { label: 'Pakistan (+92)', value: 'Pakistan (+92)' },
    { label: 'Panama (+507)', value: 'Panama (+507)' },
    { label: 'Paraguay (+595)', value: 'Paraguay (+595)' },
    { label: 'Peru (+51)', value: 'Peru (+51)' },
    { label: 'Philippines (+63)', value: 'Philippines (+63)' },
    { label: 'Poland (+48)', value: 'Poland (+48)' },
    { label: 'Portugal (+351)', value: 'Portugal (+351)' },
    { label: 'Qatar (+974)', value: 'Qatar (+974)' },
    { label: 'Romania (+40)', value: 'Romania (+40)' },
    { label: 'Russia (+7)', value: 'Russia (+7)' },
    { label: 'Rwanda (+250)', value: 'Rwanda (+250)' },
    { label: 'Saudi Arabia (+966)', value: 'Saudi Arabia (+966)' },
    { label: 'Senegal (+221)', value: 'Senegal (+221)' },
    { label: 'Serbia (+381)', value: 'Serbia (+381)' },
    { label: 'Singapore (+65)', value: 'Singapore (+65)' },
    { label: 'Slovakia (+421)', value: 'Slovakia (+421)' },
    { label: 'Slovenia (+386)', value: 'Slovenia (+386)' },
    { label: 'South Africa (+27)', value: 'South Africa (+27)' },
    { label: 'South Korea (+82)', value: 'South Korea (+82)' },
    { label: 'Spain (+34)', value: 'Spain (+34)' },
    { label: 'Sri Lanka (+94)', value: 'Sri Lanka (+94)' },
    { label: 'Sudan (+249)', value: 'Sudan (+249)' },
    { label: 'Sweden (+46)', value: 'Sweden (+46)' },
    { label: 'Switzerland (+41)', value: 'Switzerland (+41)' },
    { label: 'Syria (+963)', value: 'Syria (+963)' },
    { label: 'Taiwan (+886)', value: 'Taiwan (+886)' },
    { label: 'Tajikistan (+992)', value: 'Tajikistan (+992)' },
    { label: 'Tanzania (+255)', value: 'Tanzania (+255)' },
    { label: 'Thailand (+66)', value: 'Thailand (+66)' },
    { label: 'Tunisia (+216)', value: 'Tunisia (+216)' },
    { label: 'Turkey (+90)', value: 'Turkey (+90)' },
    { label: 'Uganda (+256)', value: 'Uganda (+256)' },
    { label: 'Ukraine (+380)', value: 'Ukraine (+380)' },
    { label: 'United Arab Emirates (+971)', value: 'United Arab Emirates (+971)' },
    { label: 'United Kingdom (+44)', value: 'United Kingdom (+44)' },
    { label: 'United States (+1)', value: 'United States (+1)' },
    { label: 'Uruguay (+598)', value: 'Uruguay (+598)' },
    { label: 'Uzbekistan (+998)', value: 'Uzbekistan (+998)' },
    { label: 'Venezuela (+58)', value: 'Venezuela (+58)' },
    { label: 'Vietnam (+84)', value: 'Vietnam (+84)' },
    { label: 'Yemen (+967)', value: 'Yemen (+967)' },
    { label: 'Zambia (+260)', value: 'Zambia (+260)' },
    { label: 'Zimbabwe (+263)', value: 'Zimbabwe (+263)' },
  ];
  